--- a/.github/workflows/skip.yml
+++ b/.github/workflows/skip.yml
@@ -26,7 +26,7 @@
       - run: exit 0
 
   tests:
-    name: ${{ matrix.os }} / ${{ matrix.python-version
+    name: ${{ matrix.os }} / ${{ matrix.python-version }}
     # we do not need os specific runners here, using linux is quicker
     runs-on: ubuntu-latest
     strategy:
@@ -34,4 +34,4 @@
         os: [Ubuntu, MacOS, Windows]
         python-version: [2.7, 3.5, 3.6, 3.7, 3.8]
     steps:
-      - run: exit 0
+      - run: exit 0